WEB_DEV/flask/flask_random_code/simple_blog_app_flask/project/views/login.py
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import login_required, logout_user, login_user
from werkzeug.security import check_password_hash
from datetime import datetime, date

from project.models import UserModel
from project.forms import LoginForm


log = Blueprint('log', __name__)

year = datetime.now().year
post_date = date.today()


@log.route("/login", methods=['GET', 'POST'])
def login():
    """ login user, if there is no sush user then you will be 
    redirected to register page """
    
    form = LoginForm()
    
    if form.validate_on_submit():
        try:
            user = UserModel.query.filter_by(user=form.user.data).first()
            password = check_password_hash(user.password, form.password.data)
            if password == True and user is not None:
                login_user(user)
                
                flash(f"User:'{user.user}' - logged in.")
                return redirect(url_for('main.home'))
            
        except AttributeError:
                flash(f"There is no - username:'{form.user.data}'. Please register username.")
                return redirect(url_for('user.register_user'))
            
    return render_template('user_pages/login.html', form=form, year=year)


@log.route('/logout')
@login_required
def logout():
    """ logout user and redirect to home page"""
    
    logout_user()
    
    flash(f"Logged out.")
    return redirect(url_for('main.home'))

WEB_DEV/flask/flask_random_code/simple_blog_app_flask/project/views/main.py
from flask import Blueprint, render_template, request, redirect
from datetime import datetime, date
from flask_login import login_required
from project.models import PostModel


main = Blueprint('main', __name__)

year = datetime.now().year
post_date = date.today()


@main.route('/')
def home():
    """ gets all post of all users and show 5 posts per page """

    header_text = "All Posts"

    page = request.args.get('page', 1, type=int)

    blog_posts = PostModel.query.order_by(PostModel.post_date.asc()) \
                                            .paginate(page=page, 
                                                        per_page=5, 
                                                        error_out=False)

    return render_template("index.html", blog_posts=blog_posts, 
                                            year=year, 
                                            header_text=header_text, 
                                            page_name="all posts")


@main.route('/my_posts/<int:current_user>')
@login_required
def user_posts(current_user):
    """ gets all post of all users """

    header_text = "Your Posts"

    blog_posts = PostModel.query.filter_by(user_id=current_user) \
                                            .order_by(PostModel.post_date.asc()) \
                                            .all()

    return render_template("index.html", blog_posts=blog_posts, 
                                            year=year, 
                                            header_text=header_text, 
                                            page_name="user posts")


@main.route('/post/<int:index>')
def post_selected(index):
    """ opens selected post, if you are current_user=true then you will see 
    update/delete buttons, else just read-only post """

    blog_posts = PostModel.query.get(index)

    return render_template("post_pages/post.html", blog_posts=blog_posts, 
                                                    year=year)


@main.route('/search', methods=['GET', 'POST'])
def post_search():
    """ case-insensitive search with wildcards,
    '|' symbol represents the operation 'OR' """

    search_value = request.form.get("search")

    header_text = f"Search result: {search_value}"

    if request.method == 'POST':
        blog_posts = PostModel.query.filter((PostModel.title.ilike(f'%{search_value}%')) |
                                            (PostModel.subtitle.ilike(f'%{search_value}%')) |
                                            (PostModel.text.ilike(f'%{search_value}%'))) \
                                            .order_by(PostModel.post_date.asc()) \
                                            .all()

        return render_template("index.html", blog_posts=blog_posts, 
                                                year=year, 
                                                header_text=header_text)

    else:
        return redirect(request.url)

WEB_DEV/flask/flask_random_code/simple_blog_app_flask/project/views/posts.py
from flask import Blueprint, render_template, flash, redirect, url_for, abort, request
from datetime import datetime, date
from flask_login import login_required, current_user
from sqlalchemy.exc import IntegrityError
from werkzeug.utils import secure_filename
import os
import random
import string


from project.models import PostModel
from project.forms import AddUpdatePostForm
from project import db, app


posts = Blueprint('posts', __name__)

year = datetime.now().year
post_date = date.today()



def generate_random_string(length):
    """ create random string combination """

    characters = string.ascii_uppercase + string.digits + string.ascii_lowercase
    random_string = ''.join(random.choice(characters) for _ in range(length))
    
    return random_string


@posts.route("/add", methods=['GET', 'POST'])
@login_required
def post_add():
    """ adds new post if user is logged in """

    form = AddUpdatePostForm()
    
    random_number = generate_random_string(20)

    try:
        if form.validate_on_submit():
            file = form.image.data

            if file != "" and file is not None:
                # Save the file - "current_dir, folder_to_upload, random string, filename"
                file.save(os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                          + app.config['UPLOAD_FOLDER']
                          + f"{random_number}"
                          + secure_filename(file.filename))

                image = f"{random_number}" + \
                    secure_filename(form.image.data.filename)
            else:
                image = "no_image.jpg"

            new_post = PostModel(
                title=form.title.data,
                subtitle=form.subtitle.data,
                text=form.text.data,
                post_date=f"{post_date} by {current_user.user}",
                user_id=current_user.id,
                image=image
            )

            db.session.add(new_post)
            db.session.commit()

            flash(f"Post:'{form.title.data}' was created.")
            return redirect(url_for('main.home'))

    except IntegrityError:
        flash(
            f"'{form.title.data}' - this title exists, please select diffrent title.")
        return redirect(request.url)

    return render_template('post_pages/add_post.html', form=form,
                                                        year=year)


@posts.route("/update/<int:index>", methods=['GET', 'POST'])
@login_required
def post_update(index):
    """ updates post if current_user is logged in, else this won't work, you 
    won't see update button in post page """

    form = AddUpdatePostForm()

    blog_posts = PostModel.query.get(index)

    # First grab the file
    random_number = generate_random_string(20)

    if blog_posts.author != current_user:
        abort(403)

    if form.validate_on_submit():
        try:
            file = form.image.data

            blog_posts.title = form.title.data
            blog_posts.subtitle = form.subtitle.data
            blog_posts.text = form.text.data
            blog_posts.post_date = f"{post_date} by {current_user.user}"

            if file != "" and file is not None:
                # Save the file - "current_dir, folder_to_upload, filename" and database
                file.save(os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
                          + app.config['UPLOAD_FOLDER']
                          + f"{str(random_number)}"
                          + secure_filename(file.filename))

                blog_posts.image = f"{str(random_number)}" + \
                                        secure_filename(file.filename)

            db.session.commit()

            flash(f"Post:'{blog_posts.title}' was updated.")
            return redirect(url_for('main.home'))

        except IntegrityError:
            flash(
                f"'{form.title.data}' - this title exists, please select diffrent title.")
            return redirect(request.url)

    if request.method == "GET":

        form.title.data = blog_posts.title
        form.subtitle.data = blog_posts.subtitle
        form.text.data = blog_posts.text

        return render_template('post_pages/update_post.html', form=form,
                                                                year=year)


@posts.route("/delete/<int:index>", methods=['GET', 'POST'])
@login_required
def delete_post(index):
    """ deletes post if current_user is logged in, else this won't work, you 
    won't see delete button in post page """

    blog_posts = PostModel.query.get(index)

    if blog_posts.author != current_user:
        abort(403)

    db.session.delete(blog_posts)
    db.session.commit()

    flash(f"Post:'{blog_posts.title}' was deleted.")
    return redirect(url_for('main.home'))

WEB_DEV/flask/flask_random_code/simple_blog_app_flask/project/views/user.py
from flask import Blueprint, render_template, flash, redirect, url_for, request
from flask_login import login_required, logout_user
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime, date

from project.models import UserModel, PostModel
from project.forms import RegisterForm, UpdateUserForm, UpdatePasswordForm
from project import db


user = Blueprint('user', __name__)

year = datetime.now().year
post_date = date.today()


@user.route("/register", methods=['GET', 'POST'])
def register_user():
    """ register new user and redirect to login page"""

    form = RegisterForm()

    if form.validate_on_submit():
        if form.password.data == form.confirm_password.data:
            try:
                new_user = UserModel(
                    user=form.user.data,
                    password=generate_password_hash(form.password.data)
                )

                db.session.add(new_user)
                db.session.commit()

                flash(f"User:'{form.user.data}' registration was successful.")
                return redirect(url_for('log.login'))

            except:
                flash(
                    f"Can't create - username:'{form.user.data}'. Please select different username.")
                return redirect(request.url)

    return render_template('user_pages/register.html', form=form,
                           year=year)


@user.route("/delete/user/<int:current_user>", methods=['POST'])
@login_required
def delete_user(current_user):
    """ delete user if current_user is logged in """

    password = request.form.get('password')

    user_data = UserModel.query.filter_by(id=current_user).first()

    if user_data:
        if check_password_hash(user_data.password, password):
            posts = PostModel.query.filter_by(user_id=user_data.id).all()

            for post in posts:
                db.session.delete(post)

            db.session.delete(user_data)
            db.session.commit()

            logout_user()

            flash(f"User '{user_data.user}' was deleted.")
            return redirect(url_for('main.home'))

        else:
            flash("Password is incorrect.")

    else:
        flash("User not found.")

    return redirect(url_for('main.home'))


@user.route("/edit_username/<int:current_user>", methods=['GET', 'POST'])
@login_required
def edit_username(current_user):
    """ update username if current_user is logged in """

    form = UpdateUserForm()

    user_data = UserModel.query.get(current_user)

    try:
        if form.validate_on_submit() and \
                check_password_hash(user_data.password, form.password.data) == True and \
                check_password_hash(user_data.password, form.confirm_password.data) == True:

            user_data.user = form.user.data

            db.session.commit()

            flash(f"Changed to new username:'{user_data.user}'.")
            return redirect(url_for('main.home'))

        elif form.validate_on_submit() and \
            (check_password_hash(user_data.password, form.password.data) == False or
             check_password_hash(user_data.password, form.confirm_password.data) == False):

            flash(f"Please type correct password for '{user_data.user}'.")
            return redirect(request.url)

        if request.method == "GET":

            form.user.data = user_data.user

            return render_template('user_pages/edit_user.html', form=form,
                                   year=year)

    except:
        flash(
            f"Can't create - username:'{form.user.data}'. Please select different username.")
        # redirect to same page. Basically refresh page.
        return redirect(request.url)


@user.route("/edit_password/<int:current_user>", methods=['GET', 'POST'])
@login_required
def edit_password(current_user):
    """ update password if current_user is logged in """

    form = UpdatePasswordForm()

    user_data = UserModel.query.get(current_user)

    if form.password.data == form.confirm_password.data:

        if form.validate_on_submit() and \
                check_password_hash(user_data.password, form.old_password.data) == True:

            user_data.password = generate_password_hash(form.password.data)

            db.session.commit()

            flash(f"Password was changed.")
            return redirect(url_for('main.home'))

        elif form.validate_on_submit() and \
                check_password_hash(user_data.password, form.old_password.data) == False:
            flash(f"Password you typed is incorrect.")
            return redirect(request.url)

    else:
        flash(f"New password didn't match. Please try again.")
        # redirect to same page. Basically refresh page.
        return redirect(request.url)

    return render_template('user_pages/edit_password.html', form=form,
                           year=year)

WEB_DEV/flask/flask_random_code/simple_blog_app_flask/project/templates/base_pages/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>My Blog</title>
    <link href="https://fonts.googleapis.com/css2?family=Raleway" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
</head>

<body>

    <div class="container">

        {% include 'base_pages/navbar.html' %}

        {% block content %}

        {% endblock %}

    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>

</body>

</html>

WEB_DEV/flask/flask_random_code/simple_blog_app_flask/project/templates/base_pages/navbar.html
<nav class="navbar navbar-expand-lg">

  <div class="container">
    <a class="navbar-brand" href="{{ url_for('main.home')}}">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon nti"></span>
    </button>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">

        {% if current_user.is_authenticated %}

        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('main.user_posts', current_user=current_user.id) }}">My Posts</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('posts.post_add') }}">Add Post</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('log.logout') }}">Log Out</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Settings
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{{ url_for('user.edit_username', current_user=current_user.id) }}">Change
                Username</a></li>
            <li><a class="dropdown-item" href="{{ url_for('user.edit_password', current_user=current_user.id) }}">Change
                Password</a></li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item" data-bs-toggle="modal" data-bs-target="#del_modal">Delete User</a></li>
          </ul>
        </li>

        <div class="modal" tabindex="-1" role="dialog" id="del_modal">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title">Delete Account</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <p>Are you sure you want to delete your account? This will delete your account with all posts in it.</p>
                <form action="{{ url_for('user.delete_user', current_user=current_user.id) }}" method="POST">
                  <div class="form-group">
                    <label for="password">Password:</label>
                    <input type="password" class="form-control" id="password" name="password">
                  </div>
                  <hr>
                  <input class="btn btn-post" type="submit" value="Delete">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </form>
              </div>
            </div>
          </div>
        </div>
        

        {% else %}

        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('log.login') }}">Log In</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user.register_user') }}">Register</a>
        </li>

        {% endif %}
      </ul>
    </div>

    <form class="form-inline my-2 my-lg-0" method="post" action="{{ url_for('main.post_search') }}">
      <div class="input-group">
        <input class="form-control search-entry" type="search" placeholder="Search" aria-label="Search" name="search">
        <div class="input-group-append">
          <button class="btn btn-outline-success search-btn" type="submit">Search</button>
        </div>
      </div>
    </form>
  </div>

</nav>