WEB_DEV/flask/flask_random_code/order_managment_web_app_flask/views/edit.py
from datetime import datetime

import psycopg2
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
import config


# Blueprint
edit_table = Blueprint("edit_table", __name__)
# Import DB conn
params = config.sql_db
# Import current date
year = datetime.now().year
date_today = datetime.today().strftime('%Y-%m-%d')
# name for "label" "id" "name". Look at add.html for loop
label_names = ['Company', 'Client', 'Phone Number',
               'Order Name', 'Order Term', 'Status', 'Comments']


@edit_table.route('/add_new', methods=['GET', 'POST'])
def add_order():
    """ ADD NEW RECORD FORM """

    if 'user' in session:
        # if methods is POST get all data from FORM and add it to SQL. Update_date doesn't have request.form,
        # it just auto fills cell with current date.
        if request.method == 'POST':
            company = request.form.get('Company')
            client = request.form.get('Client')
            phone_number = request.form.get('Phone Number')
            order_name = request.form.get('Order Name')
            order_term = request.form.get('Order Term')
            status = request.form.get('Status')
            comments = request.form.get('Comments')
            update_date = f'{date_today}'

            con = psycopg2.connect(**params)
            cur = con.cursor()
            cur.execute('''INSERT INTO orders (company, client, phone_number, order_name,
                order_term, status, comments, update_date) VALUES
                (%s, %s, %s, %s, %s, %s, %s, %s)''',
                        (company, client, phone_number, order_name,
                         order_term, status, comments, update_date,))
            con.commit()
            con.close()

            # if everything is ok, then you will be redirected to main page with table
            return redirect(url_for('main_table.order_table'))

        return render_template('edit_pages/add.html', label_names=label_names, year=year, date_today=date_today, view_value='form')

    else:
        return redirect(url_for('login_bp.login'))


@edit_table.route('/update_order/<int:row_id>', methods=['GET', 'POST'])
def update_order(row_id):
    """ UPDATE RECORD FORM """

    if 'user' in session:
        # if methods is POST get all data from FORM and add it to SQL.
        # if method is GET, gets all data from SQL and fills form with that data,
        # look at html file update.html
        # Update_date doesn't have request.form, it just auto fills cell with current date.
        row_id_ = None

        if request.method == 'POST':
            row_id_ = row_id

            company = request.form.get('Company')
            client = request.form.get('Client')
            phone_number = request.form.get('Phone Number')
            order_name = request.form.get('Order Name')
            order_term = request.form.get('Order Term')
            status = request.form.get('Status')
            comments = request.form.get('Comments')
            update_date = f'{date_today}'

            con = psycopg2.connect(**params)
            cur = con.cursor()
            cur.execute('''UPDATE orders SET company = %s, client = %s, phone_number = %s, order_name = %s, 
                        order_term = %s, status = %s, comments = %s, update_date = %s WHERE id = %s''',
                        (company, client, phone_number, order_name,
                         order_term, status, comments, update_date, row_id_))
            con.commit()
            con.close()

            # if everything is ok, then you will be redirected to main page with table
            return redirect(url_for('main_table.order_table'))

        if request.method == "GET":
            row_id_ = row_id

            con = psycopg2.connect(**params)
            cur = con.cursor()
            cur.execute(
                f"""SELECT * FROM orders WHERE ID=%s""", (row_id_,))
            order_items = cur.fetchone()
            con.close()

            # create dict with data to fill form
            order_data_dict = {label_names[i]: order_items[i+1]
                               for i in range(0, len(label_names))}

        return render_template('edit_pages/update.html', label_names=label_names, year=year, date_today=date_today,
                               order_data_dict=order_data_dict, order_items=order_items, view_value='form')

    else:
        return redirect(url_for('login_bp.login'))


@edit_table.route('/delete/<int:row_id>', methods=['GET', 'POST'])
def delete_order(row_id):
    if 'user' in session:
        """ DELETE RECORD """

        row_id_ = None

        if request.method == "POST":
            conn = psycopg2.connect(**params)
            cur = conn.cursor()
            cur.execute("DELETE FROM orders WHERE id = %s", (row_id,))
            conn.commit()
            conn.close()

            flash(f"Order was deleted.")

            return redirect(url_for('main_table.order_table'))

        elif request.method == "GET":
            row_id_ = row_id

        return render_template('edit_pages/delete.html', row_id=row_id_, year=year, view_value='form')

    else:
        return redirect(url_for('login_bp.login'))

WEB_DEV/flask/flask_random_code/order_managment_web_app_flask/templates/edit_pages/add.html
{% extends 'base/base.html' %}

{% block content %}
<!-- center all widgets like table -->
<div class="parent">
  <div class="child-add-new">
    <div class="container">
      <!-- create form -->
      <form method="POST" action="{{ url_for('edit_table.add_order') }}">
        <!-- add labels and inputs for first rows FOR and ID has to be same to fix label to input and etc.-->
        {% for name in label_names[0:-3] %}
        <div class="form-group">
          <label for="{{ name }}">{{ name }}: </label>
          <input class="form-control" id="{{ name }}" type="text" placeholder="Enter {{ name }}" name="{{ name }}"
            maxlength="70">
        </div>
        {% endfor %}
        <!-- ################## -->
        <!-- add term date picker-->
        {% for name in label_names[4:5] %}
        <div class="form-group">
          <label for="{{ name }}">{{ name }}: </label>
          <input class="form-control" id="{{ name }}" type="date" value="{{ date_today }}" min="{{ year }}-01-01"
            max="3000-12-31" name="{{ name }}" maxlength="70">
        </div>
        {% endfor %}
        <!-- ################## -->
        <!-- add status combo box -->
        {% for name in label_names[5:6] %}
        <div class="form-group">
          <label for="{{ name }}">{{ name }}: </label>
          <select class="form-select" id="{{ name }}" name="{{ name }}" maxlength="70">
            <option selected value="IN PROCESS">IN PROCESS</option>
            <option value="FINISHED">FINISHED</option>
            </select>
        </div>
        {% endfor %}
        <!-- ################## -->
        <!-- add comments areafield with 1000max elements you can write and 5rows height-->
        {% for name in label_names[6:7] %}
        <div class="form-group">
          <label for="{{ name }}">{{ name }}: </label>
          <textarea class="form-control" id="{{ name }}" type="text" placeholder="Enter {{ name }}" name="{{ name }}"
            rows="5" maxlength="1000" style="resize: none;"></textarea>
          <br>
        </div>
        {% endfor %}
        <!-- ################## -->
        <!-- submit new record -->
        <button type="submit" class="btn btn-dark button-add-new-update">Submit</button>
        <!-- ################## -->
      </form>
      <!-- ################## -->
    </div>
  </div>
</div>
{% endblock %}

WEB_DEV/flask/flask_random_code/order_managment_web_app_flask/templates/edit_pages/delete.html
{% extends 'base/base.html' %}

{% block content %}
<div class="card card-delete">
  <div class="card-body">
    <h5 class="card-title">Delete</h5>
    <p class="card-text">Are you sure you want to delete this order?</p>
    <form class="d-flex" action="{{ url_for('edit_table.delete_order', row_id=row_id ) }}" method="POST">
      <td><button type="submit" class="btn btn-secondary delete-btn">Delete</button></td>
    </form>
    <form class="d-flex" action="{{ url_for('main_table.order_table') }}">
      <td><button type="submit" class="btn btn-secondary cancel-btn">Cancel</button></td>
    </form>
  </div>
</div>
{% endblock %}

WEB_DEV/flask/flask_random_code/order_managment_web_app_flask/templates/edit_pages/update.html
{% extends 'base/base.html' %}

{% block content %}
<!-- center all widgets like table -->
<div class="parent">
  <div class="child-add-new">
    <div class="container"></div>
    <!-- create form -->
    <form method="POST" action="{{ url_for('edit_table.update_order', row_id=order_items[0]) }}">
      <!-- add labels and inputs for first rows FOR and ID has to be same to fix label to input and etc.-->
      {% for name in label_names[0:-3] %}
      <div class="form-group">
        <label for="{{ name }}">{{ name }}: </label>
        <input class="form-control" id="{{ name }}" type="text" placeholder="Enter {{ name }}" name="{{ name }}"
          maxlength="70" value="{{ order_data_dict[name] }}">
      </div>
      {% endfor %}
      <!-- ################## -->
      <!-- add term date picker-->
      {% for name in label_names[4:5] %}
      <div class="form-group">
        <label for="{{ name }}">{{ name }}: </label>
        <input class="form-control" id="{{ name }}" type="date" min="{{ year }}" max="3000-12-31" name="{{ name }}"
          maxlength="70" value="{{ order_data_dict[name] }}">
      </div>
      {% endfor %}
      <!-- ################## -->
      <!-- add status combo box -->
      {% for name in label_names[5:6] %}
      <div class="form-group">
        <label for="{{ name }}">{{ name }}: </label>
        <select class="form-select" id="{{ name }}" name="{{ name }}" maxlength="70">
          <option value="IN PROCESS">IN PROCESS</option>
          <option value="FINISHED">FINISHED</option>
          </select>
      </div>
      {% endfor %}
      <!-- ################## -->
      <!-- add comments areafield with 1000max elements you can write and 5rows height-->
      {% for name in label_names[6:7] %}
      <div class="form-group">
        <label for="{{ name }}">{{ name }}: </label>
        <textarea class="form-control" id="{{ name }}" type="text" placeholder="Enter {{ name }}" name="{{ name }}"
          rows="5" maxlength="1000" style="resize: none;">{{ order_data_dict[name] }}</textarea>
      </div>
      {% endfor %}
      <!-- ################## -->
      <br>
      <!-- ################## -->
      <!-- submit new record -->
      <button type="submit" class="btn btn-dark button-add-new-update">Submit</button>
      <!-- ################## -->
    </form>
    <!-- ################## -->
  </div>
</div>
{% endblock %}